[project]
name = "backend"
version = "0.1.0"
description = "Backend server for Computer Science Capstone for WGU. A machine learning app that determines whether a bank loan applicant is likely to default."
authors = [
    {name = "Yali Miranda",email = "ymiran7@wgu.edu"}
]
requires-python = ">=3.13"
dependencies = [
    "scikit-learn (>=1.7.0,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
