import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
/*Free logo generated by logo.com */
import logo from '../assets/western-governors-financial-high-resolution-logo-grayscale-transparent.png'

function LandingPage() {
    const [serverReady, setServerReady] = useState(false);

    useEffect(() => {
        const checkServerStatus = async () => {
            try {
                const res = await fetch("http://localhost:8000/");
                const data = await res.json();
                if (data.message === "Loan Default Prediction API is running.") {
                    setServerReady(true);
                }
            } catch (err) {
                setTimeout(checkServerStatus, 1000);
            }
        }

        checkServerStatus();
    }, []);

    if (!serverReady) {
        return (
            <div className="min-h-screen flex flex-col justify-center items-center bg-slate-900 text-white text-center px-4">
                <img src={logo} alt="Western Governors Financial logo" className="h-32 sm:h-40 md:h-64 lg:h-96 mb-8" />
                <p className="text-xl font-medium mb-4">Starting server process. Please wait...</p>
                <div className="w-12 h-12 border-4 border-blue-500 border-t-transparent rounded-full animate-spin"></div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-gradient-to-br from-slate-900 to-blue-900 text-white flex flex-col justify-center items-center px-4">

            {/* Logo + Title*/}
            <div className="flex flex-col items-center mb-8">
                <img src={logo} alt="Western Governors Financial logo" className="h-32 sm:h-40 md:h-64 lg:h-96 mb-20" />
                <h1 className="lg:text-5xl md:text-4xl font-bold text-center">
                    Loan Default Predictor
                </h1>
            </div>

            {/* Flavor Text */}
            <p className="text-lg md:text-xl text-slate-300 mb-10 max-w-xl text-center">
                Make smarter decisions using machine learning. Instantly evaluate risk with our predictive model.
            </p>

            {/* Navigation Buttons */}
            <div className="flex flex-col sm:flex-row gap-4">
                <Link to="/predict">
                    <button className="px-6 py-3 bg-blue-600 hover:bg-blue-700 rounded-xl text-white font-semibold shadow">
                        Try the Predictor
                    </button>
                </Link>
                <Link to="/learn">
                    <button className="px-6 py-3 bg-white text-blue-700 hover:bg-slate-100 rounded-xl font-semibold shadow">
                        Learn More
                    </button>
                </Link>
            </div>
        </div>
    )
}

export default LandingPage